function response(id, label, effects, results) {
  return Object.freeze({ id, label, effects: Object.freeze(effects || {}), results: Object.freeze(results) });
}

function event(id, category, title, evidence, roomId, roles, choices, options = {}) {
  return Object.freeze({
    id, category, title, evidence, roomId,
    roles: Object.freeze(roles), choices: Object.freeze(choices),
    weight: options.weight || 1,
    cooldownSteps: options.cooldownSteps || 4,
    incompatibleTags: Object.freeze(options.incompatibleTags || []),
    requiresTags: Object.freeze(options.requiresTags || [])
  });
}

const VOYAGE_EVENT_FAMILIES = Object.freeze([
  event('departure-handoff', 'navigation', 'Departure watch handoff', 'The cruise crew is ready to take the ship, but the departure watch has two unresolved navigation notes.', 'bridge', ['command', 'navigation'], [
    response('full-handoff', 'Review both notes with the incoming watch', { roles: ['navigation'], repair: { navigation: 0.035 }, fatigue: 0.008, tags: ['watch-handoff-verified'] }, ['The two watches reconcile the notes and transfer a clean course picture.', 'The handoff takes longer than planned, but the incoming watch understands the remaining uncertainty.', 'A missed discrepancy forces navigation to repeat part of the departure solution.']),
    response('captain-brief', 'Give the incoming watch a short captain’s brief', { roles: ['command'], fatigue: -0.005, tags: ['watch-handoff-brief'] }, ['The short brief focuses the watch on the route’s real margins.', 'The watch understands the priorities, though one technical note remains open.', 'The brief is too compressed and the incoming watch inherits an avoidable question.'])
  ], { weight: 2 }),
  event('course-margin-review', 'navigation', 'Course margin review', 'Navigation finds that the current arrival margin is narrower than the plan assumed.', 'navigation-cartography', ['navigation', 'command'], [
    response('refine-course', 'Rebuild the course solution', { roles: ['navigation'], cost: { powerMWh: 0.18 }, repair: { navigation: 0.045 }, tags: ['course-margin-restored'] }, ['The rebuilt solution restores a comfortable arrival margin.', 'The new solution improves the margin but retains a small correction later.', 'The recalculation exposes a larger uncertainty and adds work to the next watch.']),
    response('protect-reserves', 'Keep the route and protect reserves', { tags: ['narrow-course-margin'], deferred: [{ afterSteps: 3, systemId: 'navigation', delta: -0.035, unlessTag: 'course-margin-restored', message: 'The narrow arrival margin requires an additional correction.' }] }, ['The ship holds course and preserves its reserves.', 'The route remains safe, though the next correction window becomes important.', 'Small errors accumulate and the crew must recover them later.'])
  ]),
  event('sensor-navigation-disagreement', 'navigation', 'Sensors and navigation disagree', 'The star tracker and inertial solution place the ship on slightly different lines.', 'sensor-control', ['navigation', 'science'], [
    response('cross-calibrate', 'Cross-calibrate both systems', { roles: ['navigation', 'science'], cost: { powerMWh: 0.25 }, repair: { navigation: 0.04, sensors: 0.04 }, tags: ['frames-cross-calibrated'] }, ['The two frames converge and the course solution stabilizes.', 'Most of the disagreement is removed, with a small residual left for later.', 'The calibration run fails to isolate the source of the disagreement.']),
    response('trust-inertial', 'Continue on the inertial solution', { tags: ['sensor-disagreement-deferred'], deferred: [{ afterSteps: 2, systemId: 'sensors', delta: -0.04, message: 'The unresolved frame disagreement complicates a later observation.' }] }, ['The inertial solution remains steady through the next leg.', 'The ship stays on course, but science loses some pointing confidence.', 'The unresolved error grows enough to cost a later correction.'])
  ]),
  event('avoidance-maneuver', 'navigation', 'Micrometeoroid avoidance', 'Forward tracking resolves a compact particle stream crossing the ship’s path.', 'bridge', ['flight', 'navigation'], [
    response('thread-gap', 'Fly through the measured gap', { roles: ['flight', 'navigation'], cost: { propellantKg: 18 }, tags: ['precise-avoidance'] }, ['The ship crosses the stream without a strike.', 'A few grains hit the outer shield, but the pressure hull remains untouched.', 'The timing error exposes the forward shield to a glancing impact.']),
    response('wide-diversion', 'Take the wider diversion', { cost: { propellantKg: 48, foodKg: 2, waterKg: 1.5 }, tags: ['conservative-diversion'] }, ['The diversion clears the stream with room to spare.', 'The route is safe but costs more time than expected.', 'A late burn spends extra propellant before the ship clears the stream.'])
  ]),
  event('local-system-insertion', 'navigation', 'Local-system insertion', 'The destination star’s motion is now measurable and the crew must choose an insertion profile.', 'bridge', ['flight', 'navigation'], [
    response('survey-insertion', 'Enter on a broad survey arc', { roles: ['navigation', 'science'], cost: { propellantKg: 32 }, tags: ['survey-insertion'] }, ['The arc gives sensors a clean first look at the system.', 'The ship enters safely, though the first survey pass is shorter than planned.', 'The entry geometry obscures part of the system and requires a second pass.']),
    response('direct-insertion', 'Enter on the shortest safe line', { roles: ['flight'], cost: { propellantKg: 18 }, tags: ['direct-insertion'] }, ['The flight crew completes a precise direct insertion.', 'The ship enters safely with little margin for a course correction.', 'The direct line requires a hard correction near the end of the burn.'])
  ]),
  event('final-approach', 'navigation', 'Final approach calibration', 'The destination frame is resolving into local stars, bodies, and safe navigation boundaries.', 'bridge', ['navigation', 'science', 'flight'], [
    response('calibrate-arrival', 'Calibrate the local frame', { roles: ['navigation', 'science'], cost: { powerMWh: 0.2 }, repair: { navigation: 0.08, sensors: 0.04 }, tags: ['arrival-calibrated'] }, ['The local frame resolves cleanly and the ship is ready for manual flight.', 'The frame is usable, with one low-confidence region marked for caution.', 'The calibration needs a manual flight correction before local operations begin.']),
    response('manual-approach', 'Keep the approach under manual control', { roles: ['flight'], repair: { navigation: 0.02 }, tags: ['manual-arrival'] }, ['The flight crew carries the ship smoothly into local space.', 'The approach succeeds with a wider safety boundary.', 'The crew recovers a late alignment error before entering the local frame.'])
  ], { weight: 2 }),

  event('coolant-pump-wear', 'engineering', 'Coolant pump wear', 'A primary thermal-loop pump is losing efficiency under cruise load.', 'thermal-control', ['engineering'], [
    response('replace-pump', 'Replace the pump', { roles: ['engineering'], requires: { resources: { maintenanceKg: 120 } }, cost: { maintenanceKg: 120 }, repair: { thermal: 0.26 }, tags: ['pump-replaced'] }, ['Engineering installs and tests the spare pump.', 'The replacement works, though vibration remains above baseline.', 'The new pump needs a second shutdown after a poor first alignment.']),
    response('reduce-reactor-load', 'Reduce reactor load and service the bearings', { roles: ['engineering'], cost: { powerMWh: 0.45 }, repair: { thermal: 0.12 }, tags: ['reduced-thermal-load'], deferred: [{ afterSteps: 3, resourceKey: 'foodKg', delta: -3, message: 'The reduced reactor load lengthens the leg and consumes additional provisions.' }] }, ['The bearings stabilize at the lower load.', 'The loop holds, but cruise performance remains limited.', 'The pump continues to shed efficiency and must be watched closely.'])
  ]),
  event('power-converter-loss', 'engineering', 'Power conversion loss', 'A converter bank is shedding useful energy as heat.', 'power-control', ['engineering'], [
    response('service-converter', 'Service the converter bank', { roles: ['engineering'], requires: { resources: { maintenanceKg: 30 } }, cost: { maintenanceKg: 30 }, repair: { power: 0.2, thermal: 0.03 }, tags: ['converter-serviced'] }, ['The bank returns to its expected conversion range.', 'Efficiency improves, though one module remains below baseline.', 'The first repair uncovers damage in a neighboring module.']),
    response('shed-load', 'Shed nonessential loads', { cost: { powerMWh: 0.3 }, tags: ['nonessential-loads-off'], deferred: [{ afterSteps: 2, systemId: 'medical', delta: -0.025, message: 'Deferred medical and exercise loads reduce the crew’s recovery margin.' }] }, ['Essential systems retain a stable power margin.', 'The load shed works, with a growing backlog of deferred work.', 'The crew must cut deeper than expected to protect life support.'])
  ]),
  event('injector-imbalance', 'engineering', 'Propulsion injector imbalance', 'The drive’s thrust trace shows a repeating imbalance across one injector group.', 'engineering', ['engineering', 'flight'], [
    response('hot-balance', 'Balance the injectors under load', { roles: ['engineering', 'flight'], requires: { systems: { propulsion: 0.45 } }, cost: { propellantKg: 22 }, repair: { propulsion: 0.18 }, tags: ['injectors-balanced'] }, ['The thrust trace settles without interrupting the leg.', 'The balance improves, but the crew schedules a later inspection.', 'The under-load adjustment worsens one injector before the crew stabilizes it.']),
    response('shutdown-inspection', 'Pause thrust for a full inspection', { roles: ['engineering'], cost: { foodKg: 2.5, waterKg: 1.5 }, repair: { propulsion: 0.24 }, tags: ['injectors-inspected'] }, ['The crew finds the worn component and restores the injector group.', 'The inspection removes the worst imbalance but lengthens the leg.', 'The shutdown reveals that the available replacement needs fabrication.'])
  ]),
  event('radiator-obstruction', 'engineering', 'Radiator flow obstruction', 'One heat-rejection panel is running hotter than its neighboring sections.', 'thermal-control', ['engineering'], [
    response('flush-loop', 'Flush the affected loop', { roles: ['engineering'], cost: { waterKg: 4, maintenanceKg: 12 }, repair: { thermal: 0.17 }, tags: ['radiator-flushed'] }, ['The obstruction clears and panel temperatures equalize.', 'Flow improves, but the panel stays slightly above baseline.', 'The flush moves debris deeper into the loop and creates more work.']),
    response('isolate-panel', 'Isolate the panel and lower output', { cost: { powerMWh: 0.55 }, tags: ['radiator-panel-isolated'], deferred: [{ afterSteps: 2, systemId: 'thermal', delta: -0.03, unlessTag: 'radiator-flushed', message: 'The isolated radiator panel narrows the thermal margin.' }] }, ['The remaining panels carry the reduced load.', 'Temperatures stabilize near the top of the safe range.', 'The reduced array struggles during the next high-load operation.'])
  ]),
  event('attitude-control-wear', 'engineering', 'Attitude-control degradation', 'A control cluster responds slowly during fine pointing.', 'engineering', ['engineering', 'flight'], [
    response('replace-valves', 'Replace the worn control valves', { roles: ['engineering'], requires: { resources: { maintenanceKg: 20 } }, cost: { maintenanceKg: 20 }, repair: { propulsion: 0.08, navigation: 0.04 }, tags: ['attitude-valves-replaced'] }, ['Fine pointing returns to normal.', 'Response improves enough for routine navigation.', 'One replacement valve sticks during the functional check.']),
    response('software-compensation', 'Compensate in the flight solution', { roles: ['flight', 'navigation'], cost: { powerMWh: 0.12 }, tags: ['attitude-software-compensation'] }, ['The revised control law masks the slow cluster.', 'The compensation works except during the fastest slews.', 'The control law creates an oscillation that demands manual damping.'])
  ]),
  event('pressure-zone-leak', 'engineering', 'Pressure-zone leak', 'Atmosphere monitors find a slow pressure loss near a service penetration.', 'life-support', ['engineering', 'life-support'], [
    response('trace-and-seal', 'Trace and seal the leak', { roles: ['engineering', 'life-support'], requires: { resources: { maintenanceKg: 16 } }, cost: { maintenanceKg: 16 }, repair: { hull: 0.13, 'life-support': 0.06 }, tags: ['pressure-leak-sealed'] }, ['The crew finds the cracked seal and verifies the repair.', 'Pressure holds, though the repair remains on the inspection list.', 'The first seal fails and the zone loses more air before isolation.']),
    response('isolate-pressure-zone', 'Isolate the affected zone', { tags: ['zone-isolated'], deferred: [{ afterSteps: 3, crewFatigue: 0.025, message: 'The isolated zone forces longer routes and adds work to every watch.' }] }, ['The doors hold and atmosphere loss stops.', 'Isolation controls the leak but restricts access to the room.', 'A delayed door closure costs additional atmosphere before the zone seals.'])
  ]),
  event('fabrication-defect', 'engineering', 'Fabrication defect', 'Inspection finds voids in a newly fabricated batch of maintenance parts.', 'cargo-fabrication', ['engineering'], [
    response('recycle-batch', 'Recycle and rebuild the batch', { roles: ['engineering'], requires: { resources: { feedstockKg: 20, powerMWh: 0.3 } }, cost: { feedstockKg: 20, powerMWh: 0.3 }, repair: { fabrication: 0.08 }, tags: ['fabrication-batch-rebuilt'] }, ['The rebuilt parts pass inspection.', 'Most of the batch is recovered, with a smaller usable yield.', 'The second run exposes a calibration problem in the fabricator.']),
    response('reserve-good-parts', 'Keep only the parts that pass inspection', { cost: { maintenanceKg: 10 }, tags: ['maintenance-stock-reduced'] }, ['The crew identifies a small set of trustworthy parts.', 'The inspection protects quality but cuts the maintenance reserve.', 'A hidden defect slips through and threatens a later repair.'])
  ]),
  event('load-shed-recovery', 'engineering', 'Cascading load-shed recovery', 'A transient fault trips several secondary buses and leaves systems restarting out of order.', 'power-control', ['engineering', 'life-support'], [
    response('staged-restart', 'Restart each bus in a controlled sequence', { roles: ['engineering', 'life-support'], repair: { power: 0.14, 'life-support': 0.04 }, tags: ['staged-power-recovery'] }, ['Each bus returns without another trip.', 'Most systems return, but one laboratory bus remains offline.', 'An early restart retriggers the protection system and extends the outage.']),
    response('protect-critical-loads', 'Hold critical loads and defer the rest', { tags: ['secondary-buses-deferred'], deferred: [{ afterSteps: 2, systemId: 'fabrication', delta: -0.04, message: 'The deferred fabrication bus develops a calibration drift before restart.' }] }, ['Life support, navigation, and medical remain stable.', 'Critical systems hold while the deferred-work list grows.', 'A supposedly noncritical load proves necessary to another recovery task.'])
  ]),

  event('crew-fatigue', 'crew', 'Accumulated fatigue', 'Medical reports slower reaction times and rising errors across the active watch.', 'medical', ['medical', 'command'], [
    response('rotate-watch', 'Stand down the tired watch', { roles: ['command'], fatigue: -0.07, tags: ['watch-rotation-protected'] }, ['The rested watch takes over cleanly.', 'The rotation helps, though coverage is thin for several hours.', 'The handoff is rushed and one task loses continuity.']),
    response('medical-support', 'Use medical support and shorten the watch', { roles: ['medical'], requires: { resources: { medicalUnits: 2 } }, cost: { medicalUnits: 2 }, fatigue: -0.05, tags: ['fatigue-medically-supported'] }, ['The crew recovers without losing critical coverage.', 'Symptoms improve, but the next rest period remains mandatory.', 'Support masks the worst symptoms without fixing the workload.'])
  ]),
  event('minor-injury', 'crew', 'Minor crew injury', 'A crew member strains a shoulder while securing equipment after a maneuver.', 'medical', ['medical'], [
    response('treat-and-rest', 'Treat the injury and assign rest', { roles: ['medical'], requires: { resources: { medicalUnits: 1 } }, cost: { medicalUnits: 1 }, fatigue: -0.025, tags: ['injury-treated'] }, ['Treatment works and the crew member returns on a limited schedule.', 'The injury improves but restricts heavy work for the next watch.', 'Pain persists and another crew member must cover the assignment.']),
    response('restricted-duty', 'Move the crew member to restricted duty', { fatigue: 0.01, tags: ['restricted-duty'], deferred: [{ afterSteps: 2, crewFatigue: 0.02, message: 'Restricted duty leaves the remaining watch carrying extra work.' }] }, ['The new assignment protects the injury without losing coverage.', 'The watch adapts, but several tasks take longer.', 'Thin coverage pushes another crew member toward exhaustion.'])
  ]),
  event('exercise-deconditioning', 'crew', 'Deconditioning warning', 'Exercise records show that two crew members are falling below the mission target.', 'exercise-bay', ['medical'], [
    response('restore-schedule', 'Restore the full exercise schedule', { roles: ['medical'], cost: { powerMWh: 0.16, waterKg: 1 }, fatigue: -0.025, tags: ['exercise-schedule-restored'] }, ['The crew completes the missed sessions and recovery improves.', 'The schedule returns with a modest cost to other work.', 'A crowded schedule adds fatigue before the benefit appears.']),
    response('short-resistance-blocks', 'Use shorter resistance blocks during watches', { fatigue: -0.012, tags: ['exercise-blocks-adopted'] }, ['Short sessions fit the watch schedule and stop the decline.', 'The compromise slows the decline but does not fully reverse it.', 'Inconsistent sessions fail to correct the problem.'])
  ]),
  event('watch-coverage-gap', 'crew', 'Watch coverage gap', 'A repair, a medical restriction, and scheduled rest leave one watch without full role coverage.', 'briefing', ['command'], [
    response('cross-assign-crew', 'Cross-assign qualified crew', { roles: ['command'], fatigue: 0.018, tags: ['watch-cross-assigned'] }, ['The revised roster restores coverage with manageable fatigue.', 'Coverage returns, but the next watch inherits unfinished work.', 'The reassignment solves one gap and creates another.']),
    response('defer-routine-work', 'Defer routine work until the next watch', { tags: ['routine-work-deferred'], deferred: [{ afterSteps: 2, systemId: 'hull', delta: -0.025, message: 'Deferred inspection work allows minor wear to go unnoticed.' }] }, ['Critical work continues and the backlog stays controlled.', 'The backlog grows but remains visible to the next watch.', 'A deferred check hides a developing fault.'])
  ]),
  event('water-contamination', 'crew', 'Water-recovery contamination', 'The recovery loop detects an organic load above its normal treatment range.', 'hygiene-waste', ['life-support', 'medical'], [
    response('sterilize-loop', 'Sterilize and flush the loop', { roles: ['life-support'], cost: { waterKg: 12, powerMWh: 0.22 }, repair: { 'life-support': 0.12 }, tags: ['water-loop-sterilized'] }, ['The flush clears the contamination and the reserve remains safe.', 'The loop returns to service with a reduced water margin.', 'The first sterilization cycle fails and consumes extra water.']),
    response('isolate-and-ration', 'Isolate the loop and ration clean water', { cost: { waterKg: 4 }, fatigue: 0.02, tags: ['water-rationing'], deferred: [{ afterSteps: 2, crewFatigue: 0.025, message: 'Water rationing increases fatigue and lowers morale.' }] }, ['Rationing protects the clean reserve until service is possible.', 'The reserve holds, though hygiene and exercise are reduced.', 'The isolation is incomplete and part of the reserve must be discarded.'])
  ]),
  event('crop-cycle-problem', 'crew', 'Crop-cycle problem', 'Hydroponics shows uneven growth and falling nutrient uptake in one crop rack.', 'hydroponics', ['life-support', 'science'], [
    response('rebalance-crop', 'Rebalance light, water, and nutrients', { roles: ['life-support', 'science'], cost: { waterKg: 3, powerMWh: 0.12 }, repair: { 'food-production': 0.12 }, tags: ['crop-cycle-rebalanced'] }, ['The crop rack resumes steady growth.', 'Most plants recover, but the harvest will be smaller.', 'The adjustment arrives too late for part of the crop.']),
    response('harvest-early', 'Harvest the viable plants early', { cost: { foodKg: 5 }, tags: ['crop-harvested-early'] }, ['The crew saves a useful portion of the crop.', 'The early harvest prevents a total loss but reduces future variety.', 'More of the crop is lost during processing than expected.'])
  ]),
  event('morale-strain', 'crew', 'Isolation and morale strain', 'The crew briefing reveals frayed communication and growing withdrawal between watches.', 'galley-wardroom', ['command', 'medical'], [
    response('shared-meal', 'Hold a shared meal and open briefing', { requires: { resources: { foodKg: 8, waterKg: 3 } }, cost: { foodKg: 8, waterKg: 3 }, fatigue: -0.035, tags: ['crew-cohesion-restored'] }, ['The crew resolves two tensions and leaves with a common plan.', 'The meal helps, though one disagreement remains unsettled.', 'The discussion exposes deeper strain and needs follow-up.']),
    response('private-check-ins', 'Schedule private check-ins by watch', { roles: ['medical', 'command'], fatigue: -0.018, tags: ['crew-check-ins'] }, ['The check-ins surface problems before they become conflicts.', 'Several crew members respond well while others remain guarded.', 'The schedule feels formal and fails to reach the most isolated crew member.'])
  ]),

  event('faint-system-contact', 'science', 'Faint system contact', 'Long-range sensors separate a dim star and several orbiting bodies from the background.', 'sensor-control', ['science', 'navigation'], [
    response('wide-survey', 'Run a wide survey', { roles: ['science'], cost: { powerMWh: 0.5 }, contact: 'survey', tags: ['contact-wide-survey'] }, ['The survey fixes the system’s motion and identifies a solid inner world.', 'The system is confirmed, though several bodies remain unresolved.', 'Interference leaves the contact real but poorly constrained.']),
    response('record-contact', 'Record the contact and stay on course', { contact: 'detect', tags: ['contact-recorded'] }, ['The contact receives a stable route designation.', 'The route record preserves the signal with broad uncertainty.', 'The abbreviated record leaves the contact difficult to reacquire.'])
  ]),
  event('unusual-spectrum', 'science', 'Unusual spectrum', 'A nearby object shows absorption features that do not fit the first classification.', 'analysis-data', ['science'], [
    response('repeat-spectrum', 'Repeat the spectrum at higher resolution', { roles: ['science'], cost: { powerMWh: 0.32 }, tags: ['spectrum-resolved'] }, ['The second observation separates mineral, ice, and instrument features.', 'The new data narrows the possibilities without a single answer.', 'Thermal noise compromises the repeat and the classification stays open.']),
    response('compare-archives', 'Compare the signal with the ship archive', { roles: ['science'], tags: ['spectrum-archive-compared'] }, ['The archive reveals a close physical analogue.', 'The comparison rules out several explanations.', 'No archive match is close enough to resolve the signal.'])
  ]),
  event('minor-body-field', 'science', 'Minor-body field', 'The route crosses a loose family of dark minor bodies with varied surface composition.', 'sensor-control', ['science', 'navigation'], [
    response('map-field', 'Map a safe line through the field', { roles: ['science', 'navigation'], cost: { powerMWh: 0.28 }, tags: ['minor-field-mapped'] }, ['The map finds a safe line and several worthwhile observations.', 'The ship clears the field with a conservative safety margin.', 'A poorly constrained object forces an abrupt late correction.']),
    response('sample-one-body', 'Divert the local craft to one small body', { roles: ['flight', 'science'], cost: { propellantKg: 26 }, contact: 'survey', tags: ['minor-body-stop-offered'] }, ['The body becomes a well-constrained local-operation candidate.', 'The pass confirms useful material but not a safe landing area.', 'The body’s rotation prevents a close approach.'])
  ]),
  event('transient-source', 'science', 'Transient radiation source', 'A brief high-energy signal appears off the route and is already fading.', 'science', ['science'], [
    response('track-transient', 'Give the transient full sensor time', { roles: ['science'], cost: { powerMWh: 0.38 }, tags: ['transient-tracked'] }, ['The ship records the source’s rise, decay, and direction.', 'The observation captures the decay but misses the first peak.', 'Pointing delay leaves only a weak tail in the record.']),
    response('protect-operations', 'Keep sensors on navigation and ship safety', { tags: ['transient-passed'] }, ['The ship protects its current operations while logging the brief signal.', 'A low-resolution trace remains useful for the mission archive.', 'The source fades before science can establish a reliable direction.'])
  ]),
  event('resource-signature', 'science', 'Geological resource signature', 'A surveyed solid world shows mineral signatures relevant to fabrication and repair.', 'analysis-data', ['science', 'engineering'], [
    response('characterize-deposit', 'Characterize the deposit and landing uncertainty', { roles: ['science', 'engineering'], cost: { powerMWh: 0.35 }, contact: 'offer-stop', tags: ['resource-deposit-characterized'] }, ['The crew identifies a bounded landing region and a credible material estimate.', 'The world remains a useful stop, but the best deposit is not fully constrained.', 'The signal proves patchy and the stop carries significant uncertainty.']),
    response('retain-estimate', 'Keep the preliminary estimate', { contact: 'detect', tags: ['resource-estimate-preliminary'] }, ['The estimate remains in the route record for later use.', 'The contact is preserved with a wide resource range.', 'The weak estimate may not be enough to justify a later diversion.'])
  ]),
  event('conflicting-observation', 'science', 'Conflicting observation', 'Two instruments report different sizes and compositions for the same body.', 'analysis-data', ['science'], [
    response('independent-follow-up', 'Run an independent follow-up', { roles: ['science'], cost: { powerMWh: 0.26 }, tags: ['observation-reconciled'] }, ['The follow-up identifies a calibration bias and reconciles the data.', 'The disagreement narrows to one unresolved property.', 'A new inconsistency leaves the object less certain than before.']),
    response('preserve-uncertainty', 'Preserve both results and move on', { tags: ['observation-unresolved'], deferred: [{ afterSteps: 2, systemId: 'sensors', delta: -0.02, message: 'The unresolved observation complicates a later targeting solution.' }] }, ['The archive clearly records both results and their uncertainty.', 'The record is honest but offers little help to later planning.', 'The unresolved discrepancy is mistaken for a targeting error later.'])
  ]),

  event('particle-strike', 'hazard', 'High-velocity particle strike', 'A small particle hits the forward shielding. Pressure is stable, but the impact site is hot.', 'engineering', ['engineering'], [
    response('inspect-and-patch', 'Inspect and patch the shielding', { roles: ['engineering'], requires: { resources: { maintenanceKg: 24 } }, cost: { maintenanceKg: 24 }, repair: { hull: 0.15 }, tags: ['shield-patched'] }, ['The crew finds a shallow crater and restores the outer layers.', 'The patch protects the pressure hull but needs later inspection.', 'Hidden delamination makes the repair larger than the first scan suggested.']),
    response('isolate-and-monitor', 'Isolate the nearby zone and monitor it', { tags: ['impact-zone-isolated'], deferred: [{ afterSteps: 2, systemId: 'hull', delta: -0.04, unlessTag: 'shield-patched', message: 'The unpatched impact site begins to shed material under thermal cycling.' }] }, ['Isolation contains the risk until a safer work period.', 'The zone remains stable but unavailable.', 'Thermal cycling worsens the damaged outer layer.'])
  ]),
  event('radiation-front', 'hazard', 'Radiation front', 'Particle monitors detect an approaching radiation front along the current route.', 'storm-shelter', ['navigation', 'medical'], [
    response('take-shelter', 'Secure the ship and take shelter', { fatigue: 0.012, tags: ['radiation-shelter-used'] }, ['The water-lined shelter keeps crew exposure low.', 'The crew remains safe, though the long shelter period adds fatigue.', 'A rushed shutdown leaves several systems needing recovery afterward.']),
    response('alter-course', 'Burn around the strongest region', { roles: ['navigation', 'flight'], requires: { resources: { propellantKg: 36 } }, cost: { propellantKg: 36 }, tags: ['radiation-diversion'] }, ['The diversion avoids the strongest particle flux.', 'The ship skirts the front with a narrow margin.', 'The front expands during the maneuver and the crew still shelters briefly.'])
  ]),
  event('debris-region', 'hazard', 'Dust and debris region', 'The route ahead contains fine dust and intermittent larger echoes.', 'bridge', ['navigation', 'science'], [
    response('slow-and-scan', 'Reduce speed and scan a path', { roles: ['navigation', 'science'], cost: { powerMWh: 0.24, foodKg: 1.5, waterKg: 1 }, tags: ['debris-path-mapped'] }, ['The ship crosses on a well-mapped path.', 'The slower crossing avoids major impacts but adds time.', 'Several false returns force repeated course corrections.']),
    response('shielded-crossing', 'Cross behind the forward shield', { damage: { hull: 0.045 }, tags: ['shielded-debris-crossing'] }, ['The shield takes only superficial dust erosion.', 'Repeated small impacts reduce the shield margin.', 'A larger fragment strikes near an earlier repair.'])
  ]),
  event('charged-interference', 'hazard', 'Charged-particle interference', 'A changing plasma environment disrupts communications, sensors, and fine control.', 'communications', ['science', 'navigation'], [
    response('retune-arrays', 'Retune communications and sensors', { roles: ['science', 'navigation'], cost: { powerMWh: 0.2 }, repair: { sensors: 0.08, navigation: 0.03 }, tags: ['arrays-retuned'] }, ['The arrays regain stable tracking through the interference.', 'Tracking returns with reduced range.', 'The retune trades one interference band for another.']),
    response('inertial-watch', 'Hold an inertial watch until it passes', { tags: ['inertial-watch'], deferred: [{ afterSteps: 1, systemId: 'navigation', delta: -0.02, message: 'The inertial-only interval adds uncertainty to the route solution.' }] }, ['The ship holds steady until normal sensors return.', 'The watch preserves safety with a small navigation uncertainty.', 'The interference lasts longer than forecast and strains the inertial solution.'])
  ]),
  event('close-star-thermal-stress', 'hazard', 'Close-star thermal stress', 'A planned stellar pass is heating the forward hull and radiator loop faster than expected.', 'thermal-control', ['engineering', 'navigation'], [
    response('widen-pass', 'Widen the stellar pass', { roles: ['navigation'], cost: { propellantKg: 28 }, tags: ['stellar-pass-widened'] }, ['The wider line restores comfortable thermal margin.', 'Temperatures fall slowly but remain controlled.', 'The correction begins late and the hull absorbs extra heat.']),
    response('maximize-cooling', 'Hold course and maximize cooling', { roles: ['engineering'], cost: { powerMWh: 0.42 }, repair: { thermal: 0.04 }, damage: { hull: 0.025 }, tags: ['maximum-cooling-used'] }, ['The thermal loop carries the peak without exceeding limits.', 'The ship holds course with little remaining thermal margin.', 'One radiator section saturates and heats the forward structure.'])
  ]),

  event('resource-world-diversion', 'stop', 'Optional resource-world diversion', 'A surveyed world can supply repair feedstock, but the diversion will cost time and propellant.', 'briefing', ['command', 'navigation', 'science'], [
    response('mark-resource-stop', 'Add the world as a local-operation stop', { requires: { tags: ['resource-deposit-characterized'] }, contact: 'mark-stop', cost: { propellantKg: 20 }, tags: ['resource-stop-authorized'] }, ['Navigation adds a bounded approach and the craft team begins planning.', 'The stop is added with a conservative landing uncertainty.', 'The approach remains possible, but the resource estimate is weaker than hoped.']),
    response('remain-on-course', 'Remain on the primary route', { tags: ['resource-stop-declined'] }, ['The ship protects its arrival margin and retains the contact.', 'The contact remains available for a future Expedition.', 'The decision preserves the route but leaves maintenance reserves tight.'])
  ], { requiresTags: ['resource-deposit-characterized'], weight: 1.5 }),
  event('emergency-repair-landing', 'stop', 'Emergency repair landing', 'A degrading ship system needs material or a stable work period that the current leg cannot provide.', 'briefing', ['command', 'engineering', 'science'], [
    response('prepare-repair-landing', 'Prepare the local craft and landing plan', { contact: 'mark-stop', cost: { propellantKg: 24 }, tags: ['emergency-landing-authorized'] }, ['The crew identifies a solid body and prepares a bounded landing operation.', 'A viable site is found with strict weather and terrain limits.', 'The first site is rejected and the approach must remain on hold.']),
    response('attempt-shipboard-repair', 'Attempt another shipboard repair', { roles: ['engineering'], requires: { resources: { maintenanceKg: 18 } }, cost: { maintenanceKg: 18 }, repair: { thermal: 0.06, power: 0.04, hull: 0.03 }, tags: ['shipboard-repair-extended'] }, ['The repair buys enough margin to continue.', 'The temporary repair holds but remains a later risk.', 'The repair consumes parts without removing the underlying fault.'])
  ], { requiresTags: ['maintenance-stock-reduced'] }),
  event('modeled-salvage', 'stop', 'Unidentified debris cluster', 'Sensors resolve an old modeled object and a loose debris field outside the primary route.', 'sensor-control', ['science', 'engineering'], [
    response('remote-inspection', 'Inspect it remotely before approaching', { roles: ['science'], cost: { powerMWh: 0.24 }, contact: 'survey', tags: ['salvage-remotely-inspected'] }, ['The inspection identifies stable debris and several unsafe fragments.', 'The object remains unidentified but its motion is well constrained.', 'Interference hides the most important part of the debris field.']),
    response('close-salvage-pass', 'Make a close salvage pass', { roles: ['flight', 'engineering'], cost: { propellantKg: 16 }, damage: { hull: 0.02 }, tags: ['salvage-pass-made'] }, ['The crew recovers a small amount of usable feedstock without contact.', 'The pass recovers little but records the object in detail.', 'A fragment strikes the shield during withdrawal.'])
  ]),
  event('distress-contact', 'stop', 'Distress contact', 'A bounded signal reports a disabled craft with failing power and uncertain position.', 'communications', ['command', 'navigation', 'engineering'], [
    response('assist-contact', 'Divert to assist', { roles: ['navigation', 'engineering'], cost: { propellantKg: 34, powerMWh: 0.3, maintenanceKg: 12 }, tags: ['distress-assist'] }, ['Asteria reaches the craft and stabilizes its power system.', 'The crew provides supplies and a safe navigation solution from a distance.', 'The contact’s position error turns the rescue into a costly search.']),
    response('remote-guidance', 'Send remote repair and navigation guidance', { roles: ['engineering', 'navigation'], cost: { powerMWh: 0.12 }, tags: ['distress-guidance'] }, ['The remote procedure restores enough power for the craft to reach safety.', 'The contact regains partial control and continues at reduced capability.', 'Signal loss interrupts the repair before power is stable.']),
    response('record-and-decline', 'Record the contact and continue', { tags: ['distress-declined'], fatigue: 0.01 }, ['The captain records the decision and preserves the primary mission.', 'The crew accepts the decision, though morale is unsettled.', 'The unresolved contact weighs on the crew through the next watch.'])
  ])
]);

const VOYAGE_EVENT_BY_ID = Object.freeze(Object.fromEntries(VOYAGE_EVENT_FAMILIES.map((entry) => [entry.id, entry])));
const VOYAGE_EVENT_COUNTS = Object.freeze(VOYAGE_EVENT_FAMILIES.reduce((counts, entry) => ({ ...counts, [entry.category]: (counts[entry.category] || 0) + 1 }), {}));

export { VOYAGE_EVENT_BY_ID, VOYAGE_EVENT_COUNTS, VOYAGE_EVENT_FAMILIES };
